baseurl = "http://kulla.me/"
title = "Stephan Kulla"
copyright = "&copy; 2016 Stephan Kulla"
languageCode = "en"
theme = "academic"

disqusShortname = ""
googleAnalytics = ""

[params]
  name = "Stephan Kulla"
  role = "Ph.D. student"
  organization = "Technical University of Munich"
  avatar = "portrait.png"
  email = "hello@kulla.me"
  address = ""
  phone = ""

  date_format = "Mon, Jan 2, 2006"
  math = false
  sharing = false

  custom_css = []
  custom_js  = []

  [params.about]
    str_interests = "Interests"
    str_education = "Education"
    interests = [
      "Mathematics education",
      "Mathematics",
      "Open educational resources"
    ]

  [[params.about.education]]
    course = "MSc in Mathematics"
    institution = "LMU Munich"
    year = 2016

  [[params.about.education]]
    course = "BSc in Physics"
    institution = "LMU Munich"
    year = 2013

  [[params.about.education]]
    course = "BSc in Mathematics"
    institution = "LMU Munich"
    year = 2012

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:hello@kulla.me"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/kulla"

[[menu.main]]
  name = "Home"
  url = "#top"
  weight = 1

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 6
